[package]
name = "solana_wallet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_wallet"

[dependencies]
anchor-lang = { version = "0.31.0", features = ["init-if-needed"] }

[features]
idl-build = ["anchor-lang/idl-build"]
